// <auto-generated />
using System;
using KimmyEsthi.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace kimmy_esthi_backend.Migrations
{
    [DbContext(typeof(KimmyEsthiDbContext))]
    [Migration("20250701033036_ScheduledAppointment")]
    partial class ScheduledAppointment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ScheduledAppointmentAppointmentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScheduledAppointmentAppointmentId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("ScheduledAppointment", b =>
                {
                    b.Property<Guid>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SkinConcerns")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AppointmentId");

                    b.ToTable("ScheduledAppointment");
                });

            modelBuilder.Entity("Appointment", b =>
                {
                    b.HasOne("ScheduledAppointment", "ScheduledAppointment")
                        .WithMany()
                        .HasForeignKey("ScheduledAppointmentAppointmentId");

                    b.Navigation("ScheduledAppointment");
                });
#pragma warning restore 612, 618
        }
    }
}
