// <auto-generated />
using System;
using KimmyEsthi.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace kimmy_esthi_backend.Migrations
{
    [DbContext(typeof(KimmyEsthiDbContext))]
    [Migration("20260103065238_Fix Foreign Key Scheduled Appointment To Client")]
    partial class FixForeignKeyScheduledAppointmentToClient
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("KimmyEsthi.Admin.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("KimmyEsthi.Appointment.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ConsentFormId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConsentFormId");

                    b.HasIndex("DateTime")
                        .IsUnique();

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("KimmyEsthi.Appointment.ScheduledAppointment", b =>
                {
                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SkinConcerns")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AppointmentId");

                    b.ToTable("ScheduledAppointment");
                });

            modelBuilder.Entity("KimmyEsthi.Client.Client", b =>
                {
                    b.Property<Guid>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("SkinConcerns")
                        .HasColumnType("TEXT");

                    b.HasKey("ClientId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("KimmyEsthi.ConsentForm.ConsentForm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("InitialedStatements")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrintedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("ConsentForm");
                });

            modelBuilder.Entity("KimmyEsthi.Appointment.Appointment", b =>
                {
                    b.HasOne("KimmyEsthi.ConsentForm.ConsentForm", "ConsentForm")
                        .WithMany()
                        .HasForeignKey("ConsentFormId");

                    b.Navigation("ConsentForm");
                });

            modelBuilder.Entity("KimmyEsthi.Appointment.ScheduledAppointment", b =>
                {
                    b.HasOne("KimmyEsthi.Client.Client", "Client")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KimmyEsthi.Appointment.Appointment", null)
                        .WithOne("ScheduledAppointment")
                        .HasForeignKey("KimmyEsthi.Appointment.ScheduledAppointment", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("KimmyEsthi.ConsentForm.ConsentForm", b =>
                {
                    b.HasOne("KimmyEsthi.Client.Client", null)
                        .WithOne("ConsentForm")
                        .HasForeignKey("KimmyEsthi.ConsentForm.ConsentForm", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KimmyEsthi.Appointment.Appointment", b =>
                {
                    b.Navigation("ScheduledAppointment");
                });

            modelBuilder.Entity("KimmyEsthi.Client.Client", b =>
                {
                    b.Navigation("ConsentForm");
                });
#pragma warning restore 612, 618
        }
    }
}
