// <auto-generated />
using System;
using KimmyEsthi.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KimmyEsthi.Migrations
{
    [DbContext(typeof(KimmyEsthiDbContext))]
    [Migration("20260228034359_Reviews1")]
    partial class Reviews1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("KimmyEsthi.Admin.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("KimmyEsthi.Appointments.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DateTime")
                        .IsUnique();

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("KimmyEsthi.Appointments.Promotion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("KimmyEsthi.Appointments.ScheduledAppointment", b =>
                {
                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SkinConcerns")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AppointmentId");

                    b.HasIndex("ClientId");

                    b.ToTable("ScheduledAppointment");
                });

            modelBuilder.Entity("KimmyEsthi.Clients.Client", b =>
                {
                    b.Property<Guid>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("SkinConcerns")
                        .HasColumnType("TEXT");

                    b.HasKey("ClientId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("KimmyEsthi.ConsentForm.ConsentAndAcknowledgement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ConsentAndAcknowledgements");
                });

            modelBuilder.Entity("KimmyEsthi.ConsentForm.ConsentForm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AppointmentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("InitialedStatements")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrintedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("ConsentForm");
                });

            modelBuilder.Entity("KimmyEsthi.ConsentForm.ConsentFormStatement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ConsentFormStatements");
                });

            modelBuilder.Entity("KimmyEsthi.ConsentForm.EmergencyContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EmergencyContacts");
                });

            modelBuilder.Entity("KimmyEsthi.ConsentForm.ProductsUsed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Products")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProductsUsed");
                });

            modelBuilder.Entity("KimmyEsthi.ConsentForm.SkincareHistoryQuestionnaire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Allergies")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Botox")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ChemPeel")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EverReceivedFacial")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HairRemoval")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastChemPeelDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastFacialDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MedicalConditions")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NegativeReaction")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Retinol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SkinType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("SkincareHistoryQuestionnaires");
                });

            modelBuilder.Entity("KimmyEsthi.Reviews.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ReviewId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("KimmyEsthi.Services.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CardContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardImgSrc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardOverlayContent")
                        .HasColumnType("TEXT");

                    b.Property<string>("CardTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("NotBookable")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("PackageItems")
                        .HasColumnType("TEXT");

                    b.Property<string>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("PromotionName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Tags")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("KimmyEsthi.Appointments.Promotion", b =>
                {
                    b.HasOne("KimmyEsthi.Appointments.Appointment", null)
                        .WithOne("Promotion")
                        .HasForeignKey("KimmyEsthi.Appointments.Promotion", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KimmyEsthi.Appointments.ScheduledAppointment", b =>
                {
                    b.HasOne("KimmyEsthi.Appointments.Appointment", null)
                        .WithOne("ScheduledAppointment")
                        .HasForeignKey("KimmyEsthi.Appointments.ScheduledAppointment", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KimmyEsthi.Clients.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("KimmyEsthi.ConsentForm.ConsentForm", b =>
                {
                    b.HasOne("KimmyEsthi.Appointments.Appointment", null)
                        .WithOne("ConsentForm")
                        .HasForeignKey("KimmyEsthi.ConsentForm.ConsentForm", "AppointmentId");

                    b.HasOne("KimmyEsthi.Clients.Client", null)
                        .WithOne("ConsentForm")
                        .HasForeignKey("KimmyEsthi.ConsentForm.ConsentForm", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KimmyEsthi.ConsentForm.SkincareHistoryQuestionnaire", b =>
                {
                    b.HasOne("KimmyEsthi.Clients.Client", null)
                        .WithOne("SkincareHistoryQuestionnaire")
                        .HasForeignKey("KimmyEsthi.ConsentForm.SkincareHistoryQuestionnaire", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KimmyEsthi.Appointments.Appointment", b =>
                {
                    b.Navigation("ConsentForm");

                    b.Navigation("Promotion");

                    b.Navigation("ScheduledAppointment");
                });

            modelBuilder.Entity("KimmyEsthi.Clients.Client", b =>
                {
                    b.Navigation("ConsentForm");

                    b.Navigation("SkincareHistoryQuestionnaire");
                });
#pragma warning restore 612, 618
        }
    }
}
