// <auto-generated />
using System;
using KimmyEsthi.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace kimmy_esthi_backend.Migrations
{
    [DbContext(typeof(KimmyEsthiDbContext))]
    [Migration("20260123055058_Services4")]
    partial class Services4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("KimmyEsthi.Admin.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("KimmyEsthi.Appointments.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DateTime")
                        .IsUnique();

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("KimmyEsthi.Appointments.Promotion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("KimmyEsthi.Appointments.ScheduledAppointment", b =>
                {
                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SkinConcerns")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AppointmentId");

                    b.HasIndex("ClientId");

                    b.ToTable("ScheduledAppointment");
                });

            modelBuilder.Entity("KimmyEsthi.Client.Client", b =>
                {
                    b.Property<Guid>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("SkinConcerns")
                        .HasColumnType("TEXT");

                    b.HasKey("ClientId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("KimmyEsthi.ConsentForm.ConsentForm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AppointmentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("InitialedStatements")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrintedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("ConsentForm");
                });

            modelBuilder.Entity("KimmyEsthi.Services.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CardContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardImgSrc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardOverlayContent")
                        .HasColumnType("TEXT");

                    b.Property<string>("CardTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("NotBookable")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("PackageItems")
                        .HasColumnType("TEXT");

                    b.Property<string>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("PromotionName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceCardType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Tags")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("KimmyEsthi.Appointments.Promotion", b =>
                {
                    b.HasOne("KimmyEsthi.Appointments.Appointment", null)
                        .WithOne("Promotion")
                        .HasForeignKey("KimmyEsthi.Appointments.Promotion", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KimmyEsthi.Appointments.ScheduledAppointment", b =>
                {
                    b.HasOne("KimmyEsthi.Appointments.Appointment", null)
                        .WithOne("ScheduledAppointment")
                        .HasForeignKey("KimmyEsthi.Appointments.ScheduledAppointment", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KimmyEsthi.Client.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("KimmyEsthi.ConsentForm.ConsentForm", b =>
                {
                    b.HasOne("KimmyEsthi.Appointments.Appointment", null)
                        .WithOne("ConsentForm")
                        .HasForeignKey("KimmyEsthi.ConsentForm.ConsentForm", "AppointmentId");

                    b.HasOne("KimmyEsthi.Client.Client", null)
                        .WithOne("ConsentForm")
                        .HasForeignKey("KimmyEsthi.ConsentForm.ConsentForm", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KimmyEsthi.Appointments.Appointment", b =>
                {
                    b.Navigation("ConsentForm");

                    b.Navigation("Promotion");

                    b.Navigation("ScheduledAppointment");
                });

            modelBuilder.Entity("KimmyEsthi.Client.Client", b =>
                {
                    b.Navigation("ConsentForm");
                });
#pragma warning restore 612, 618
        }
    }
}
